### ISSUE TITLE
LoadableItems の汎用化

### ISSUE THREAD

**Issue by sya-ri** [gKokasai/panel.kokasai.com#120]
- 現在の仕様だと LinearProgress を使う以外の選択肢を取ることができないので、変更可能にする
- 扱う値が複数ではない可能性が当然あるので `LoadableItems` → `LoadableItem`, `items` → `item` のリネームを行う

**Comment by cheichey** [comment]
やりましょうか？

**Comment by sya-ri** [comment]
> やりましょうか？

お願いします
