### ISSUE TITLE
学籍番号のバリデーション・メール送信の確認

### ISSUE THREAD

**Issue by sya-ri** [gKokasai/panel.kokasai.com#17]
https://github.com/gKokasai/api.kokasai.com/issues/12

**Comment by cheichey** [comment]
あとは xxxxxx@gunma.kosen-ac.jp に送信しますがよろしいですか の追記

**Comment by cheichey** [comment]
わたしやります

**Comment by sya-ri** [comment]
@cheichey メール送信の確認に キャンセル が無いのは意図的ですか？間違えに気づく可能性があるので修正出来るようにしてほしいです

**Comment by cheichey** [comment]
いやぁ、追加しないとなぁと思っていたのでします

**Comment by cheichey** [comment]
これcloseしていいですか

**Comment by sya-ri** [comment]
どうぞ
